// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrUHALUjOiaTpmX03mvJAF5y_7NwlJ-M',
    appId: '1:545584768284:web:e0989e23d448b60e96c6d9',
    messagingSenderId: '545584768284',
    projectId: 'campus-commute-3b26a',
    authDomain: 'campus-commute-3b26a.firebaseapp.com',
    storageBucket: 'campus-commute-3b26a.firebasestorage.app',
    measurementId: 'G-155N0NNMY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEfEYjqJk_mBbH7yTqUzcmf-5gD9BLaGM',
    appId: '1:545584768284:android:e7256c5e4153752696c6d9',
    messagingSenderId: '545584768284',
    projectId: 'campus-commute-3b26a',
    storageBucket: 'campus-commute-3b26a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu6Xf-IU7jxZzqSZIT6LeUJ9FwZw6wE88',
    appId: '1:545584768284:ios:0ffdbbcf1b41fd4296c6d9',
    messagingSenderId: '545584768284',
    projectId: 'campus-commute-3b26a',
    storageBucket: 'campus-commute-3b26a.firebasestorage.app',
    iosBundleId: 'com.example.campusCommuteClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu6Xf-IU7jxZzqSZIT6LeUJ9FwZw6wE88',
    appId: '1:545584768284:ios:0ffdbbcf1b41fd4296c6d9',
    messagingSenderId: '545584768284',
    projectId: 'campus-commute-3b26a',
    storageBucket: 'campus-commute-3b26a.firebasestorage.app',
    iosBundleId: 'com.example.campusCommuteClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrUHALUjOiaTpmX03mvJAF5y_7NwlJ-M',
    appId: '1:545584768284:web:ce795a6d0216443996c6d9',
    messagingSenderId: '545584768284',
    projectId: 'campus-commute-3b26a',
    authDomain: 'campus-commute-3b26a.firebaseapp.com',
    storageBucket: 'campus-commute-3b26a.firebasestorage.app',
    measurementId: 'G-788WYEE1XB',
  );
}
